// ── User ──────────────────────────────────────────────────
export type UserRole = 'user' | 'student' | 'teacher' | 'scholar' | 'moderator' | 'admin' | 'superadmin';

export interface User {
  id: string;
  name: string;
  nameAr?: string;
  email: string;
  role: UserRole;
  avatarUrl?: string;
  bio?: string;
  locale: string;
  isVerified: boolean;
  is2faEnabled?: boolean;
  reputationPoints?: number;
  createdAt: string;
}

// ── Course ────────────────────────────────────────────────
export interface Course {
  id: string;
  title: string;
  titleAr?: string;
  titleRu?: string;
  description?: string;
  category: string;
  level: 'beginner' | 'intermediate' | 'advanced' | 'all';
  language: string;
  thumbnailUrl?: string;
  price: number;
  currency: string;
  totalStudents: number;
  rating: number;
  totalRatings: number;
  totalLessons: number;
  durationHours: number;
  instructorName?: string;
  instructorAvatar?: string;
  isPublished: boolean;
  isFeatured: boolean;
  certificateEnabled: boolean;
  tags: string[];
  createdAt: string;
}

export interface Enrollment {
  id: string;
  courseId: string;
  userId: string;
  progress: number;
  completedLessons: string[];
  isCompleted: boolean;
  certificateUrl?: string;
  enrolledAt: string;
  completedAt?: string;
}

// ── Video ─────────────────────────────────────────────────
export interface Video {
  id: string;
  title: string;
  titleAr?: string;
  thumbnailUrl?: string;
  aiThumbnailUrl?: string;
  durationSeconds: number;
  viewCount: number;
  likeCount: number;
  commentCount: number;
  category: string;
  language: string;
  aiGenerated: boolean;
  status: 'draft' | 'processing' | 'transcoding' | 'ready' | 'failed';
  visibility: 'public' | 'private' | 'unlisted' | 'members_only';
  hlsManifestKey?: string;
  variants?: VideoVariant[];
  channelName?: string;
  channelSlug?: string;
  creatorVerified?: boolean;
  publishedAt?: string;
  createdAt: string;
}

export interface VideoVariant {
  quality: string;
  width: number;
  height: number;
  bitrate: string;
  playlistUrl: string;
}

export interface SubtitleTrack {
  language: string;
  label: string;
  fileUrl: string;
  isAutoGenerated: boolean;
}

// ── Forum ─────────────────────────────────────────────────
export interface ForumCategory {
  id: string;
  name: string;
  nameAr?: string;
  nameRu?: string;
  slug: string;
  description?: string;
  color: string;
  postCount: number;
}

export interface ForumPost {
  id: string;
  title: string;
  content: string;
  authorId: string;
  authorName: string;
  authorRole: UserRole;
  authorAvatar?: string;
  categoryName?: string;
  categorySlug?: string;
  categoryColor?: string;
  tags: string[];
  likesCount: number;
  viewsCount: number;
  repliesCount: number;
  isPinned: boolean;
  isLocked: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ForumReply {
  id: string;
  postId: string;
  content: string;
  authorName: string;
  authorRole: UserRole;
  authorAvatar?: string;
  likesCount: number;
  isAccepted: boolean;
  createdAt: string;
}

// ── AI ────────────────────────────────────────────────────
export interface AIConversation {
  id: string;
  title?: string;
  category: string;
  language: string;
  messageCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface AIMessage {
  id: string;
  conversationId: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  references?: AIReference[];
  confidenceScore?: number;
  tokensUsed?: number;
  flagged?: boolean;
  createdAt: string;
}

export interface AIReference {
  type: 'quran' | 'hadith' | 'scholar';
  surah?: number;
  verse?: number;
  collection?: string;
  text?: string;
}

// ── Quran ─────────────────────────────────────────────────
export interface QuranSurah {
  id: number;
  nameArabic: string;
  nameTransliteration?: string;
  nameEnglish?: string;
  revelationType?: 'Meccan' | 'Medinan';
  versesCount: number;
  orderIndex: number;
}

export interface QuranVerse {
  id: string;
  surahId: number;
  verseNumber: number;
  textArabic: string;
  textUthmani?: string;
  translationEn?: string;
  translationRu?: string;
  transliteration?: string;
  audioUrl?: string;
  juz?: number;
  page?: number;
}

export interface PrayerTimes {
  fajr: string;
  sunrise?: string;
  dhuhr: string;
  asr: string;
  maghrib: string;
  isha: string;
  city: string;
  date: string;
}

// ── Media ─────────────────────────────────────────────────
export interface MediaItem {
  id: string;
  title: string;
  titleAr?: string;
  description?: string;
  type: 'audio' | 'video' | 'pdf' | 'article' | 'podcast' | 'book' | 'magazine';
  url: string;
  thumbnailUrl?: string;
  category?: string;
  tags: string[];
  language: string;
  durationMinutes?: number;
  fileSizeMb?: number;
  downloadCount: number;
  viewCount: number;
  createdAt: string;
}

// ── Notification ──────────────────────────────────────────
export interface Notification {
  id: string;
  type: string;
  title: string;
  titleAr?: string;
  message?: string;
  link?: string;
  isRead: boolean;
  createdAt: string;
}

// ── Analytics ─────────────────────────────────────────────
export interface VideoAnalytics {
  date: string;
  views: number;
  uniqueViewers: number;
  watchTimeSeconds: number;
  likes: number;
  comments: number;
}

// ── Pagination ────────────────────────────────────────────
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  hasMore: boolean;
}

// ── API Response ──────────────────────────────────────────
export interface ApiError {
  error: string;
  errors?: { field: string; message: string }[];
  code?: string;
}
